version: '3.8'

services:
  food-service:
    build:
      context: ./food-service
      dockerfile: Dockerfile
    container_name: food-service
    ports:
      - "50052:50052"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - GRPC_SERVER_HOST=0.0.0.0
      - GRPC_SERVER_PORT=50052
    volumes:
      - ./food-service/prisma:/app/prisma
    networks:
      - microservice-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - GRPC_SERVER_HOST=0.0.0.0
      - GRPC_SERVER_PORT=50051
      - FOOD_SERVICE_HOST=food-service
      - FOOD_SERVICE_PORT=50052
    volumes:
      - ./order-service/prisma:/app/prisma
    depends_on:
      - food-service
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge